[general]
pretrained_model_name_or_path = "/data/Z-Image"
vae = "/data/Z-Image"
text_encoder = "/data/Z-Image/text_encoder"
tokenizer = "/data/Z-Image/tokenizer"
dataset_config = "./configs/zimage_dataset.toml"
output_dir = "/data/cc/zimage"
output_name = "zimage_full"
logging_dir = "/data/cc/zimage/logs"
log_with = "tensorboard"

max_token_length = 512
disable_chat_template = false

mixed_precision = "bf16"
full_bf16 = false
train_batch_size = 10
gradient_accumulation_steps = 1
gradient_checkpointing = true
learning_rate = 1e-5
max_grad_norm = 1.0
max_train_epochs = 20
save_every_n_epochs = 1
optimizer_type = "AdamW"
optimizer_args = ["weight_decay=0.1", "betas=0.9,0.99"]
lr_scheduler = "cosine_with_min_lr"
lr_scheduler_num_cycles = 1
lr_scheduler_min_lr_ratio = 0.1  # 1e-6 / 1e-5
#lr_scheduler_args = ["T_0=27026", "T_mult=2", "eta_min=1e-6"]
lr_warmup_steps = 33000
deepspeed = true
zero_stage = 1

sample_at_first = false

cache_latents = true
cache_latents_to_disk = true
train_text_encoder = false
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
vae_batch_size = 1
text_encoder_batch_size = 1
skip_cache_check = false
